# Generated by Django 6.0.5 on 2026-05-28 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comedian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "comedian_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bucket_pull", "Bucket Pull"),
                            ("regular", "Regular"),
                            ("golden_ticket", "Golden Ticket"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=20, unique=True)),
                (
                    "episode_number",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("episode_title", models.CharField(max_length=500)),
                ("episode_url", models.URLField()),
                ("published_at", models.DateField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guest_appearances",
                        to="pipeline.comedian",
                    ),
                ),
            ],
            options={
                "ordering": ["-episode_number"],
            },
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveSmallIntegerField()),
                ("start_seconds", models.FloatField()),
                (
                    "interview_end_line",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("interview_end_seconds", models.FloatField(blank=True, null=True)),
                (
                    "joke_book",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "comedian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="pipeline.comedian",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="pipeline.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["start_seconds"],
                "unique_together": {("episode", "set_number")},
            },
        ),
        migrations.CreateModel(
            name="Bit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bit_id", models.CharField(max_length=50)),
                ("premise", models.TextField(blank=True, null=True)),
                ("line_start", models.PositiveSmallIntegerField()),
                ("line_end", models.PositiveSmallIntegerField()),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bits",
                        to="pipeline.set",
                    ),
                ),
            ],
            options={
                "ordering": ["line_start"],
                "unique_together": {("set", "bit_id")},
            },
        ),
        migrations.CreateModel(
            name="Beat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beat_id", models.CharField(max_length=50)),
                ("line_start", models.PositiveSmallIntegerField()),
                ("line_end", models.PositiveSmallIntegerField()),
                ("premise", models.TextField(blank=True, null=True)),
                (
                    "joke_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("misdirect", "Misdirect"),
                            ("reframe", "Reframe"),
                            ("phonetic-match", "Phonetic match"),
                            ("double-meaning", "Double-meaning"),
                            ("what-if", "What-if"),
                            ("analogy", "Analogy"),
                            ("hyperbole", "Hyperbole"),
                            ("act-out", "Act-out"),
                            ("elephant-in-the-room", "Elephant-in-the-room"),
                            ("prop", "Prop"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("topics", models.JSONField(default=list)),
                (
                    "bit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beats",
                        to="pipeline.bit",
                    ),
                ),
            ],
            options={
                "ordering": ["line_start"],
                "unique_together": {("bit", "beat_id")},
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveSmallIntegerField()),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("punchline", "Punchline"),
                            ("tag", "Tag"),
                            ("fluff", "Fluff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("start_seconds", models.FloatField()),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pipeline.set",
                    ),
                ),
            ],
            options={
                "ordering": ["line_number"],
                "unique_together": {("set", "line_number")},
            },
        ),
    ]
