# Generated by Django 6.0.5 on 2026-06-21 13:28

import django.db.models.deletion
import django.utils.timezone
import pipeline.models.comedian
import pipeline.models.set
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comedian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[pipeline.models.comedian.validate_attributes],
                    ),
                ),
                ("joke_count", models.PositiveIntegerField(default=0)),
                ("has_small_joke_book", models.BooleanField(default=False)),
                ("has_medium_joke_book", models.BooleanField(default=False)),
                ("has_large_joke_book", models.BooleanField(default=False)),
                ("set_count", models.PositiveSmallIntegerField(default=0)),
                ("avg_punch_density", models.FloatField(blank=True, null=True)),
                ("avg_tag_density", models.FloatField(blank=True, null=True)),
                ("avg_bits_per_set", models.FloatField(blank=True, null=True)),
                ("avg_beats_per_set", models.FloatField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=20, unique=True)),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField()),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("guests", models.JSONField(blank=True, default=list)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("view_count", models.PositiveBigIntegerField(blank=True, null=True)),
                ("like_count", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "comment_count",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("tags", models.JSONField(blank=True, null=True)),
                ("set_count", models.PositiveSmallIntegerField(default=0)),
                ("bucket_pull_count", models.PositiveSmallIntegerField(default=0)),
                ("golden_ticket_count", models.PositiveSmallIntegerField(default=0)),
                ("regular_count", models.PositiveSmallIntegerField(default=0)),
                ("large_joke_book_count", models.PositiveSmallIntegerField(default=0)),
                ("view_like_ratio", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveSmallIntegerField()),
                ("start_seconds", models.FloatField()),
                (
                    "interview_end_line",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("interview_end_seconds", models.FloatField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=1000, null=True)),
                ("image_capture_seconds", models.FloatField(blank=True, null=True)),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[pipeline.models.set.validate_set_attributes],
                    ),
                ),
                ("bit_count", models.PositiveSmallIntegerField(default=0)),
                ("punch_density", models.FloatField(blank=True, null=True)),
                ("tag_density", models.FloatField(blank=True, null=True)),
                (
                    "comedian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="pipeline.comedian",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="pipeline.video",
                    ),
                ),
            ],
            options={
                "ordering": ["start_seconds"],
                "unique_together": {("video", "set_number")},
            },
        ),
        migrations.AddField(
            model_name="comedian",
            name="image_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pipeline.set",
            ),
        ),
        migrations.CreateModel(
            name="Bit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bit_id", models.CharField(max_length=50)),
                ("line_start", models.PositiveSmallIntegerField()),
                ("line_end", models.PositiveSmallIntegerField()),
                ("punch_density", models.FloatField(blank=True, null=True)),
                ("tag_density", models.FloatField(blank=True, null=True)),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bits",
                        to="pipeline.set",
                    ),
                ),
            ],
            options={
                "ordering": ["line_start"],
                "unique_together": {("set", "bit_id")},
            },
        ),
        migrations.CreateModel(
            name="Beat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beat_id", models.CharField(max_length=50)),
                ("line_start", models.PositiveSmallIntegerField()),
                ("line_end", models.PositiveSmallIntegerField()),
                ("premise", models.TextField(blank=True, null=True)),
                (
                    "joke_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("misdirect", "Misdirect"),
                            ("reframe", "Reframe"),
                            ("phonetic-match", "Phonetic match"),
                            ("double-meaning", "Double-meaning"),
                            ("contradiction", "Contradiction"),
                            ("analogy", "Analogy"),
                            ("hyperbole", "Hyperbole"),
                            ("elephant-in-the-room", "Elephant-in-the-room"),
                            ("anti-humor", "Anti-humor"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("joke_fields", models.JSONField(default=dict)),
                ("embedding", models.JSONField(default=list)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "bit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beats",
                        to="pipeline.bit",
                    ),
                ),
            ],
            options={
                "ordering": ["line_start"],
                "unique_together": {("bit", "beat_id")},
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveSmallIntegerField()),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("punchline", "Punchline"),
                            ("tag", "Tag"),
                            ("fluff", "Fluff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("start_seconds", models.FloatField()),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pipeline.set",
                    ),
                ),
            ],
            options={
                "ordering": ["line_number"],
                "unique_together": {("set", "line_number")},
            },
        ),
    ]
