# Generated by Django 6.0.5 on 2026-05-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="premise",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bit",
            name="premise",
            field=models.TextField(blank=True, null=True),
        ),
    ]
