# Generated by Django 6.0.5 on 2026-06-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beat",
            name="joke_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("misdirect", "Misdirect"),
                    ("reframe", "Reframe"),
                    ("phonetic-match", "Phonetic match"),
                    ("double-meaning", "Double-meaning"),
                    ("contradiction", "Contradiction"),
                    ("what-if", "What-if"),
                    ("analogy", "Analogy"),
                    ("hyperbole", "Hyperbole"),
                    ("act-out", "Act-out"),
                    ("elephant-in-the-room", "Elephant-in-the-room"),
                    ("prop", "Prop"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
