# Generated by Django 6.0.5 on 2026-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="guests",
        ),
        migrations.AddField(
            model_name="video",
            name="guests",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
