# Generated by Django 6.0.5 on 2026-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="punchline_embedding",
            field=models.JSONField(default=list),
        ),
    ]
