# Generated by Django 6.0.5 on 2026-05-29 17:13

import pipeline.models.comedian
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comedian",
            name="comedian_attributes",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[pipeline.models.comedian.validate_comedian_attributes],
            ),
        ),
    ]
