# Generated by Django 6.0.5 on 2026-05-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="like_count",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="view_count",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
