# Generated by Django 6.0.5 on 2026-06-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bit",
            old_name="punchline_tag_ratio",
            new_name="tag_density",
        ),
        migrations.RenameField(
            model_name="comedian",
            old_name="avg_punchline_tag_ratio",
            new_name="avg_tag_density",
        ),
        migrations.RenameField(
            model_name="set",
            old_name="punchline_tag_ratio",
            new_name="tag_density",
        ),
    ]
