# Generated by Django 6.0.5 on 2026-07-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="search_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
