# Generated by Django 6.0 on 2026-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="joke_book",
            field=models.CharField(
                blank=True,
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                max_length=10,
                null=True,
            ),
        ),
    ]
