# Generated by Django 6.0.5 on 2026-07-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beat",
            name="embedding",
        ),
    ]
