# Generated by Django 6.0.5 on 2026-05-28 09:49

import re
from django.db import migrations, models


def backfill_episode_number(apps, schema_editor):
    Episode = apps.get_model("pipeline", "Episode")
    for ep in Episode.objects.filter(episode_number__isnull=True):
        m = re.search(r"#(\d+)", ep.episode_title)
        if m:
            ep.episode_number = int(m.group(1))
            ep.save(update_fields=["episode_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episode",
            options={"ordering": ["-episode_number"]},
        ),
        migrations.AddField(
            model_name="episode",
            name="episode_number",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.RunPython(backfill_episode_number, migrations.RunPython.noop),
    ]
