# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_alter_beat_joke_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beat",
            name="joke_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("misdirect", "Misdirect"),
                    ("reframe", "Reframe"),
                    ("phonetic-match", "Phonetic match"),
                    ("double-meaning", "Double-meaning"),
                    ("contradiction", "Contradiction"),
                    ("analogy", "Analogy"),
                    ("hyperbole", "Hyperbole"),
                    ("elephant-in-the-room", "Elephant-in-the-room"),
                    ("anti-humor", "Anti-humor"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
