# Generated by Django 6.0.5 on 2026-05-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_set_joke_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="interview_end_line",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="interview_end_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
