# Generated by Django 6.0.5 on 2026-06-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_remove_video_guests_video_guests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bit",
            name="summary",
        ),
    ]
