# Generated by Django 6.0.5 on 2026-06-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_beat_punchline_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="combo_embedding",
            field=models.JSONField(default=list),
        ),
    ]
