# Generated by Django 6.0.5 on 2026-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_rename_bit_premise_to_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedian",
            name="comedian_attributes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
