# Generated by Django 6.0.5 on 2026-05-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_episode_like_count_episode_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="comment_count",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="tags",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
