# Generated by Django 6.0.5 on 2026-05-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_beat_premise_alter_bit_premise"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="joke_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("misdirect", "Misdirect"),
                    ("reframe", "Reframe"),
                    ("phonetic-match", "Phonetic match"),
                    ("double-meaning", "Double-meaning"),
                    ("what-if", "What-if"),
                    ("analogy", "Analogy"),
                    ("elephant-in-the-room", "Elephant-in-the-room"),
                    ("prop", "Prop"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
