# Generated by Django 6.0.5 on 2026-07-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_beatsegment_embedding_binary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beat",
            name="joke_fields",
        ),
        migrations.RemoveField(
            model_name="beat",
            name="premise",
        ),
    ]
