# Generated by Django 6.0.5 on 2026-06-08 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_beat_combo_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
