# Generated by Django 6.0.5 on 2026-07-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_alter_beat_joke_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeatSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("line_start", models.PositiveSmallIntegerField()),
                ("line_end", models.PositiveSmallIntegerField()),
                ("embedding", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="pipeline.beat",
                    ),
                ),
            ],
            options={
                "ordering": ["beat", "ordinal"],
                "unique_together": {("beat", "ordinal")},
            },
        ),
    ]
