# Generated by Django 6.0.5 on 2026-06-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_beat_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="beat",
            old_name="combo_embedding",
            new_name="embedding",
        ),
        migrations.RemoveField(
            model_name="beat",
            name="diagnostic_embedding",
        ),
        migrations.RemoveField(
            model_name="beat",
            name="key_embeddings",
        ),
        migrations.RemoveField(
            model_name="beat",
            name="premise_embedding",
        ),
        migrations.RemoveField(
            model_name="beat",
            name="punchline_embedding",
        ),
    ]
