# Generated by Django 6.0.5 on 2026-07-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0005_beatsegment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="set",
            unique_together={("video", "start_seconds")},
        ),
        migrations.RemoveField(
            model_name="set",
            name="set_number",
        ),
    ]
