# Generated by Django 6.0.5 on 2026-06-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0005_rename_combo_embedding_beat_embedding_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beat",
            name="keys",
        ),
    ]
